Show error to non-wayland users
waydroid/waydroid pull request #235
Opened 2021-11-22 19:31 UTC by pktiuk

This commit addresses issue: https://github.com/waydroid/waydroid/issues/72

2021-12-03 13:56 UTC, mkg20001 requested changes

2021-12-03 13:56 UTC, mkg20001 commented on tools/__init__.py
> +        if os.environ.get("XDG_SESSION_TYPE")!="wayland":
this likely will break using for example weston compositor

2021-12-03 15:44 UTC, pktiuk commented on tools/__init__.py
> +        if os.environ.get("XDG_SESSION_TYPE")!="wayland":
Maybe?
```python
 if os.environ.get("XDG_SESSION_TYPE")=="x11":
```

2021-12-03 15:46 UTC, mkg20001 commented on tools/__init__.py
> +        if os.environ.get("XDG_SESSION_TYPE")!="wayland":
The problem is that weston does not set XDG_SESSION_TYPE

![image](https://user-images.githubusercontent.com/7735145/144631092-1744dbac-1cce-4f2f-ad6c-e8104fb1acb1.png)

2021-12-03 15:47 UTC, mkg20001 commented on tools/__init__.py
> +        if os.environ.get("XDG_SESSION_TYPE")!="wayland":
There seems to be another way to check if a wayland server is running and can be connected (how the apps check it - since gedit for ex starts in weston when it's there, even when launched outside)

It could be checked that way instead

2021-12-11 18:43 UTC, hcsubser commented on tools/__init__.py
> +        if os.environ.get("XDG_SESSION_TYPE")!="wayland":
There is an environment variable called WAYLAND_DISPLAY if it is set that means that a wayland compositor is running, that should be used to check instead of XDG_SESSION_TYPE

2021-12-11 23:36 UTC, pktiuk commented on tools/__init__.py
> +        if os.environ.get("XDG_SESSION_TYPE")!="wayland":
@mkg20001  
Could you check it?

2021-12-12 00:10 UTC, mkg20001 commented on tools/__init__.py
> +        if os.environ.get("XDG_SESSION_TYPE")!="wayland":
yes, that one works

so it should be

```suggestion
        if not os.environ.get("WAYLAND_DISPLAY"):
```

![image](https://user-images.githubusercontent.com/7735145/145695600-5c7b3758-5557-48c4-88e6-a152a9259e7b.png)

2021-12-12 00:12 UTC, mkg20001 commented on tools/__init__.py
> +            logging.error("Wayland session not detected. Only Wayland session manager is supported.")
```suggestion
            logging.error("Wayland session not detected. Only Wayland session manager is supported.")
            logging.error("If you're unable to use wayland you can use the weston compositor instead.")
```

2021-12-12 19:16 UTC, pktiuk commented
I think it can be merged now :D

2021-12-12 19:35 UTC, electrikjesus commented
I will add it to the test list for this week then

2022-01-09 19:56 UTC, electrikjesus approved these changes
This works as expected in testing. Approved on my end

2022-01-10 05:33 UTC, erfanoabdi commented
this breaks ubuntu touch

2022-01-10 05:33 UTC, closed without merging

2022-01-21 19:58 UTC, mkg20001 commented
@erfanoabdi how? An exception could be made or some more checks could be done

2022-01-21 22:31 UTC, pktiuk commented
> @erfanoabdi how? An exception could be made or some more checks could be done

It is easier to just dismiss contribution instead of giving valuable feedback how to fix it.

2022-01-22 00:09 UTC, Fuseteam commented
because ubuntu-touch does not set `$XDG_SESSION_TYPE` to wayland, it sets it to `mir` while still supporting wayland apps