Prevent session start as root
waydroid/waydroid pull request #246
Opened 2021-12-03 14:05 UTC by mkg20001

the user might accidently end up doing session start from a sudo shell
prevent it, otherwise we end up with our files being owned by root and the application working not so well

2022-01-09 20:45 UTC, electrikjesus commented
There are changes needed for this to work as intended. Please look at my corrections here and resubmit https://github.com/electrikjesus/anbox-halium/commit/5054fe29bd973698fd8f871711a937b0314467ef

2022-01-09 20:47 UTC, electrikjesus commented
Actually, ignore my correction, I misunderstood what this was checking on.

2022-01-21 19:54 UTC, mkg20001 commented
So it's just the `and` instead of `&&`? Crazy language this python

2022-05-07 12:44 UTC, Fuseteam commented
what is blocking this PR?

2022-05-26 16:05 UTC, septatrix requested changes

2022-05-26 16:05 UTC, septatrix commented on tools/actions/session_manager.py
> +    if home != "/root" and os.getuid() == 0:
What if the root user has a different home directory? Might be better to check if the owner of `$HOME` is equal to the current user id

2022-05-26 18:00 UTC, mkg20001 commented on tools/actions/session_manager.py
> +    if home != "/root" and os.getuid() == 0:
This is basically never the case, but I get your point, this might also cover other possible edge cases.

2022-07-09 16:43 UTC, kj7rrv commented on tools/actions/session_manager.py
> +    if home != "/root" and os.getuid() == 0:
Why isn't just `os.getuid() == 0` enough?

2022-07-10 11:14 UTC, septatrix commented on tools/actions/session_manager.py
> +    if home != "/root" and os.getuid() == 0:
Because this is intended to prevent accidentally running this as user when `HOME` is still the directory of an unprivileged user. Some distributions configure `sudo` to preserve this variable so starting this with sudo would result in writing files as root in the users home directory. Normally running this as root however should still be allowed which is why only `UID == 0` is too strict

2022-07-14 16:39 UTC, aleasto commented
Waydroid stores the android's data in home which inevitaly includes files owned by root. I'm not sure this helps.

2022-07-14 20:06 UTC, Fuseteam commented
isn't that why @septatrix suggested checking the owner of $HOME matches the current user?

2022-08-15 18:58 UTC, JamiKettunen commented
What about similarly preventing accidental runs of [`show-full-ui`](https://github.com/waydroid/waydroid/blob/1eba546/tools/actions/app_manager.py#L106) or [`first-launch`](https://github.com/waydroid/waydroid/blob/1eba546/tools/actions/initializer.py#L199), or should those be handled by separate PR(s) due to being out-of-scope?

2022-08-16 21:39 UTC, Fuseteam commented
i think a separate PR would be better depending on how complicate it would make this one

2022-10-20 13:15 UTC, JamiKettunen commented on tools/actions/session_manager.py
> +    if home != "/root" and os.getuid() == 0:
Could leave a `FIXME` comment above here that `root` could have a different `$HOME` as well and that something like `getent passwd root | cut -d: -f6` should be used to get it instead of hardcoding it as `/root`.

2023-01-07 20:16 UTC, JamiKettunen commented on tools/actions/session_manager.py
> +    if home != "/root" and os.getuid() == 0:
@mkg20001 would you mind adding the `FIXME` as per my previous comment from a few months back? alternatively you could also implement getting the root user's `$HOME` properly too instead of hardcoding it as `/root`

2023-01-07 20:16 UTC, JamiKettunen commented
@aleasto Aside from [my comment](https://github.com/waydroid/waydroid/pull/246#discussion_r1000611095) still being unresolved, do you think this is ready for merge?

2023-01-07 20:44 UTC, aleasto commented
No, this is fundamentally wrong.

`sudo env | grep HOME` gives `/root`, making this check useless

2023-01-07 21:56 UTC, JamiKettunen commented
Ah nvm I see the issue now, this only "fixes" the issue on distributions where `sudo -E` is the default (examples being???), anyway this indeed needs to be reworked or else it prevents using Waydroid when signed in as root user and running a Wayland session etc.

2023-01-15 15:59 UTC, closed without merging